{% set name = "xarray-einstats" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/arviz-devs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ec4b98130191e49c5d74d56d5bfcd349eaaced7e9f6d653c0df9800c884e6034

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<312]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.4,<4
  run:
    - python
    - numpy >=2.0
    - scipy >=1.14
    - xarray >=2024.07.0
  run_constrained:
    - numba >=0.55

test:
  source_files:
    - tests
  imports:
    - xarray_einstats
  commands:
    - pip check
    - pytest -vv tests
  requires:
    - pip
    - pytest
    - numba >=0.55
    - einops

about:
  home: https://github.com/arviz-devs/xarray-einstats
  summary: Stats, linear algebra and einops for xarray.
  description: |
    xarray-einstats is an open source Python library part of the ArviZ project. It acts as a bridge between the xarray
    library for labelled arrays and libraries for raw arrays such as NumPy or SciPy.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://einstats.python.arviz.org
  dev_url: https://github.com/arviz-devs/xarray-einstats

extra:
  recipe-maintainers:
    - ericmjl
    - OriolAbril
