{% set name = "xarray-einstats" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/arviz-devs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de1a96d32738ce131ecacc64c75f33e254f8c30526227b6f06f99203bd66856b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<311]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.4,<4
  run:
    - python
    - numpy >=1.25
    - scipy >=1.11
    - xarray >=2023.06.0
  run_constrained:
    - numba >=0.55

# E   ModuleNotFoundError: No module named 'einops'
{% set ignore_tests = " --ignore=tests/test_einops.py" %}
test:
  source_files:
    - tests
  imports:
    - xarray_einstats
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }}
  requires:
    - pip
    - pytest
    - numba >=0.55

about:
  home: https://github.com/arviz-devs/xarray-einstats
  summary: Stats, linear algebra and einops for xarray.
  description: |
    xarray-einstats is an open source Python library part of the ArviZ project. It acts as a bridge between the xarray
    library for labelled arrays and libraries for raw arrays such as NumPy or SciPy.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://einstats.python.arviz.org
  dev_url: https://github.com/arviz-devs/xarray-einstats

extra:
  recipe-maintainers:
    - ericmjl
    - OriolAbril
